services:
  - type: web
    name: cryptoclash-app
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: NODE_ENV=production node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
